### ISSUE TITLE
trim_arg_blocks.R: Warning message:  In eval(e, x, parent.frame()): 强制过程中产生了NA

### ISSUE THREAD

**Issue by yangwukaidi** [CshlSiepelLab/bird_capuchino_analysis#1]
I refer to the article you named " Genomic islands of differentiation in a rapid avian radiation have been driven by recent selective sweeps " for research. 
This is the command line I used in running arg-sample .
_arg-sample -s LG01.sites --popsize 1000000 -r 1.5e-8 -m 2.5e-8 -c 10 --ntimes 10 --maxtime 1e6 --randomize-phase 1.0 --unphased --sample-phase 10 --resample-window-iters 1 --resample-window 10000 -n 100_

After running arg-sample, I used the scripts you uploaded on github(bird_capuchino_analysis/ARG_analysis at master · CshlSiepelLab/bird_capuchino_analysis (github.com)) for further analysis.
But when I used trim_arg_blocks.R  to filter and trim ARG blocks, it got an error with the following:
_Warning message:
In eval(e, x, parent.frame()): 强制过程中产生了NA
Warning message:
In eval(e, x, parent.frame()): 强制过程中产生了NA_

And  two files are output: ARGblock-coordinates-trimmed.txt is an empty document, the contents of ARGblock-coordinates-info.txt is " number of analyzed scaffolds is 1.  number of ARG blocks with at least 100 MCMC iterations, of size at least 120000 bp is 0.  total length of these ARG blocks is: 0.  number of ARG blocks with at least 100 MCMC iterations, but shorter than 120000 bp is 0. total length of these ARG blocks is: 0. "
I tried the same procedure with the example file from test1 you provided, and the results were the same.
How can I solve this problem?

**Comment by AndreMonc** [comment]
I had this exact issue as well, and I realized it was because my filename format was different than that used in the capuchino analysis. When I updated my filenames, the script worked. I used the command below to quickly change all my filenames to the correct format using a txt file with the updated names:

`for file in *.smc.gz; do read line;  mv -v "${file}" "${line}";  done < new_smc_filenames.txt`
